version: '3.8'
services:
  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
  telegram_bot:
    build: .
    volumes:
      - .:/app
    command: ruby telegram_bot/telegram_bot_listener.rb
